### ISSUE TITLE
Linking against too great a version of glibc

### ISSUE THREAD

**Issue by JonathanHelianthicusDoe** [TCOperations/releases#5]
Trying to run the Tooniversal launcher on Ubuntu 18.04 (the latest LTS version of Ubuntu, i.e. probably what most Linux users are running) looks like this:

```
$ ./Tooniversal-Launcher
[18171] Error loading Python lib '/tmp/_MEItFayYj/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/_MEItFayYj/libpython3.7m.so.1.0)
```

Ubuntu 18.04 uses glibc 2.27. glibc is backwards-compatible, **not** forwards-compatible, so it makes sense to build on as old of a system as is still supported (e.g. Ubuntu 16.04, [which is still supported until April 2021](https://wiki.ubuntu.com/Releases)). You could also build on Debian oldstable, or even CentOS.

**Comment by ComradeNapCal** [comment]
I had this same problem when I ran the game on LTS. 
They most likely forgot to test the game on LTS when they where porting the game to Linux.

**Comment by CrankySupertoon** [comment]
Have the same issue on Ubuntu 19_10 based distro

**Comment by TCOperations** [comment]
Thank you for reporting this issue!

Our Python 3 build now has this error rectified. Tooniversal should be playable on any Ubuntu distribution older than Ubuntu 18.04 (or libc >= 2.27).

Please reopen this issue if this is still a problem!
